name: example
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Krysl/initializer.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  initializer_annotation: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  initializer: ^0.0.1
  build_runner: ^2.2.0
