# See https://github.com/google/mono_repo.dart for details on this file
sdk:
- pubspec
- stable

stages:
- analyzer_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
- unit_test:
  - test:

cache:
  directories:
  - .dart_tool/build
