name: initializer
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  build_config: ^1.1.0
  glob: ^2.1.0
  initializer_annotation: ^0.1.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  source_gen_test: ^1.0.3
  test: ^1.16.0
