name: initializer_annotation
description: Classes and helper functions that support initialization code generation via the `initializer` package.
version: 0.1.0
repository: https://github.com/Krysl/initializer.dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1
