name: initializer_annotation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
