name: initializer_test
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.1
  dart_style: ^2.2.4
  initializer: ^0.1.0
  meta: ^1.8.0
  source_gen: ^1.2.2
  source_gen_test: ^1.0.3
  test: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
